# Generated by Django 6.0.5 on 2026-06-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pokemon_images'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('F', 'Fuego'), ('E', 'Eléctrico'), ('T', 'Tierra'), ('A', 'Agua'), ('PS', 'Psíquico'), ('L', 'Lagartija'), ('V', 'Volador'), ('P', 'Planta')], max_length=30),
        ),
    ]
