# Generated by Django 6.0.5 on 2026-06-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_picture_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('V', 'Volador'), ('E', 'Eléctrico'), ('PS', 'Psíquico'), ('L', 'Lagartija'), ('P', 'Planta'), ('T', 'Tierra'), ('A', 'Agua'), ('F', 'Fuego')], max_length=30),
        ),
    ]
